/**
 * @fileoverview
 * @enhanceable
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!

var jspb = require('google-protobuf');
var goog = jspb;
var global = Function('return this')();

var google_api_annotations_pb = require('../google/api/annotations_pb.js');
var userPb_user_pb = require('../userPb/user_pb.js');
goog.exportSymbol('proto.booksPb.Book', null, global);
goog.exportSymbol('proto.booksPb.BookCategory', null, global);
goog.exportSymbol('proto.booksPb.BookMap', null, global);
goog.exportSymbol('proto.booksPb.GetBookRequest', null, global);
goog.exportSymbol('proto.booksPb.GetBookViaAuthorRequest', null, global);
goog.exportSymbol('proto.booksPb.UpdateBookRequest', null, global);

/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.booksPb.Book = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, proto.booksPb.Book.repeatedFields_, null);
};
goog.inherits(proto.booksPb.Book, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  proto.booksPb.Book.displayName = 'proto.booksPb.Book';
}
/**
 * List of repeated fields within this message type.
 * @private {!Array<number>}
 * @const
 */
proto.booksPb.Book.repeatedFields_ = [5,6];



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto suitable for use in Soy templates.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     com.google.apps.jspb.JsClassTemplate.JS_RESERVED_WORDS.
 * @param {boolean=} opt_includeInstance Whether to include the JSPB instance
 *     for transitional soy proto support: http://goto/soy-param-migration
 * @return {!Object}
 */
proto.booksPb.Book.prototype.toObject = function(opt_includeInstance) {
  return proto.booksPb.Book.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Whether to include the JSPB
 *     instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.booksPb.Book} msg The msg instance to transform.
 * @return {!Object}
 */
proto.booksPb.Book.toObject = function(includeInstance, msg) {
  var f, obj = {
    isbn: jspb.Message.getFieldWithDefault(msg, 1, 0),
    title: jspb.Message.getFieldWithDefault(msg, 2, ""),
    author: jspb.Message.getFieldWithDefault(msg, 3, ""),
    maincategory: (f = msg.getMaincategory()) && proto.booksPb.BookCategory.toObject(includeInstance, f),
    categorylistList: jspb.Message.toObjectList(msg.getCategorylistList(),
    proto.booksPb.BookCategory.toObject, includeInstance),
    tagsList: jspb.Message.getField(msg, 6),
    mapbookMap: (f = msg.getMapbookMap()) ? f.toObject(includeInstance, proto.booksPb.BookCategory.toObject) : [],
    mapnameMap: (f = msg.getMapnameMap()) ? f.toObject(includeInstance, undefined) : []
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.booksPb.Book}
 */
proto.booksPb.Book.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.booksPb.Book;
  return proto.booksPb.Book.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.booksPb.Book} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.booksPb.Book}
 */
proto.booksPb.Book.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {number} */ (reader.readInt64());
      msg.setIsbn(value);
      break;
    case 2:
      var value = /** @type {string} */ (reader.readString());
      msg.setTitle(value);
      break;
    case 3:
      var value = /** @type {string} */ (reader.readString());
      msg.setAuthor(value);
      break;
    case 4:
      var value = new proto.booksPb.BookCategory;
      reader.readMessage(value,proto.booksPb.BookCategory.deserializeBinaryFromReader);
      msg.setMaincategory(value);
      break;
    case 5:
      var value = new proto.booksPb.BookCategory;
      reader.readMessage(value,proto.booksPb.BookCategory.deserializeBinaryFromReader);
      msg.addCategorylist(value);
      break;
    case 6:
      var value = /** @type {string} */ (reader.readString());
      msg.addTags(value);
      break;
    case 7:
      var value = msg.getMapbookMap();
      reader.readMessage(value, function(message, reader) {
        jspb.Map.deserializeBinary(message, reader, jspb.BinaryReader.prototype.readString, jspb.BinaryReader.prototype.readMessage, proto.booksPb.BookCategory.deserializeBinaryFromReader);
         });
      break;
    case 8:
      var value = msg.getMapnameMap();
      reader.readMessage(value, function(message, reader) {
        jspb.Map.deserializeBinary(message, reader, jspb.BinaryReader.prototype.readInt64, jspb.BinaryReader.prototype.readString);
         });
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.booksPb.Book.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.booksPb.Book.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.booksPb.Book} message
 * @param {!jspb.BinaryWriter} writer
 */
proto.booksPb.Book.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getIsbn();
  if (f !== 0) {
    writer.writeInt64(
      1,
      f
    );
  }
  f = message.getTitle();
  if (f.length > 0) {
    writer.writeString(
      2,
      f
    );
  }
  f = message.getAuthor();
  if (f.length > 0) {
    writer.writeString(
      3,
      f
    );
  }
  f = message.getMaincategory();
  if (f != null) {
    writer.writeMessage(
      4,
      f,
      proto.booksPb.BookCategory.serializeBinaryToWriter
    );
  }
  f = message.getCategorylistList();
  if (f.length > 0) {
    writer.writeRepeatedMessage(
      5,
      f,
      proto.booksPb.BookCategory.serializeBinaryToWriter
    );
  }
  f = message.getTagsList();
  if (f.length > 0) {
    writer.writeRepeatedString(
      6,
      f
    );
  }
  f = message.getMapbookMap(true);
  if (f && f.getLength() > 0) {
    f.serializeBinary(7, writer, jspb.BinaryWriter.prototype.writeString, jspb.BinaryWriter.prototype.writeMessage, proto.booksPb.BookCategory.serializeBinaryToWriter);
  }
  f = message.getMapnameMap(true);
  if (f && f.getLength() > 0) {
    f.serializeBinary(8, writer, jspb.BinaryWriter.prototype.writeInt64, jspb.BinaryWriter.prototype.writeString);
  }
};


/**
 * optional int64 isbn = 1;
 * @return {number}
 */
proto.booksPb.Book.prototype.getIsbn = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 1, 0));
};


/** @param {number} value */
proto.booksPb.Book.prototype.setIsbn = function(value) {
  jspb.Message.setField(this, 1, value);
};


/**
 * optional string title = 2;
 * @return {string}
 */
proto.booksPb.Book.prototype.getTitle = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 2, ""));
};


/** @param {string} value */
proto.booksPb.Book.prototype.setTitle = function(value) {
  jspb.Message.setField(this, 2, value);
};


/**
 * optional string author = 3;
 * @return {string}
 */
proto.booksPb.Book.prototype.getAuthor = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 3, ""));
};


/** @param {string} value */
proto.booksPb.Book.prototype.setAuthor = function(value) {
  jspb.Message.setField(this, 3, value);
};


/**
 * optional BookCategory mainCategory = 4;
 * @return {?proto.booksPb.BookCategory}
 */
proto.booksPb.Book.prototype.getMaincategory = function() {
  return /** @type{?proto.booksPb.BookCategory} */ (
    jspb.Message.getWrapperField(this, proto.booksPb.BookCategory, 4));
};


/** @param {?proto.booksPb.BookCategory|undefined} value */
proto.booksPb.Book.prototype.setMaincategory = function(value) {
  jspb.Message.setWrapperField(this, 4, value);
};


proto.booksPb.Book.prototype.clearMaincategory = function() {
  this.setMaincategory(undefined);
};


/**
 * Returns whether this field is set.
 * @return {!boolean}
 */
proto.booksPb.Book.prototype.hasMaincategory = function() {
  return jspb.Message.getField(this, 4) != null;
};


/**
 * repeated BookCategory categoryList = 5;
 * If you change this array by adding, removing or replacing elements, or if you
 * replace the array itself, then you must call the setter to update it.
 * @return {!Array.<!proto.booksPb.BookCategory>}
 */
proto.booksPb.Book.prototype.getCategorylistList = function() {
  return /** @type{!Array.<!proto.booksPb.BookCategory>} */ (
    jspb.Message.getRepeatedWrapperField(this, proto.booksPb.BookCategory, 5));
};


/** @param {!Array.<!proto.booksPb.BookCategory>} value */
proto.booksPb.Book.prototype.setCategorylistList = function(value) {
  jspb.Message.setRepeatedWrapperField(this, 5, value);
};


/**
 * @param {!proto.booksPb.BookCategory=} opt_value
 * @param {number=} opt_index
 * @return {!proto.booksPb.BookCategory}
 */
proto.booksPb.Book.prototype.addCategorylist = function(opt_value, opt_index) {
  return jspb.Message.addToRepeatedWrapperField(this, 5, opt_value, proto.booksPb.BookCategory, opt_index);
};


proto.booksPb.Book.prototype.clearCategorylistList = function() {
  this.setCategorylistList([]);
};


/**
 * repeated string tags = 6;
 * If you change this array by adding, removing or replacing elements, or if you
 * replace the array itself, then you must call the setter to update it.
 * @return {!Array.<string>}
 */
proto.booksPb.Book.prototype.getTagsList = function() {
  return /** @type {!Array.<string>} */ (jspb.Message.getField(this, 6));
};


/** @param {!Array.<string>} value */
proto.booksPb.Book.prototype.setTagsList = function(value) {
  jspb.Message.setField(this, 6, value || []);
};


/**
 * @param {!string} value
 * @param {number=} opt_index
 */
proto.booksPb.Book.prototype.addTags = function(value, opt_index) {
  jspb.Message.addToRepeatedField(this, 6, value, opt_index);
};


proto.booksPb.Book.prototype.clearTagsList = function() {
  this.setTagsList([]);
};


/**
 * map<string, BookCategory> mapBook = 7;
 * @param {boolean=} opt_noLazyCreate Do not create the map if
 * empty, instead returning `undefined`
 * @return {!jspb.Map<string,!proto.booksPb.BookCategory>}
 */
proto.booksPb.Book.prototype.getMapbookMap = function(opt_noLazyCreate) {
  return /** @type {!jspb.Map<string,!proto.booksPb.BookCategory>} */ (
      jspb.Message.getMapField(this, 7, opt_noLazyCreate,
      proto.booksPb.BookCategory));
};


proto.booksPb.Book.prototype.clearMapbookMap = function() {
  this.getMapbookMap().clear();
};


/**
 * map<int64, string> mapName = 8;
 * @param {boolean=} opt_noLazyCreate Do not create the map if
 * empty, instead returning `undefined`
 * @return {!jspb.Map<number,string>}
 */
proto.booksPb.Book.prototype.getMapnameMap = function(opt_noLazyCreate) {
  return /** @type {!jspb.Map<number,string>} */ (
      jspb.Message.getMapField(this, 8, opt_noLazyCreate,
      null));
};


proto.booksPb.Book.prototype.clearMapnameMap = function() {
  this.getMapnameMap().clear();
};



/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.booksPb.BookCategory = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.booksPb.BookCategory, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  proto.booksPb.BookCategory.displayName = 'proto.booksPb.BookCategory';
}


if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto suitable for use in Soy templates.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     com.google.apps.jspb.JsClassTemplate.JS_RESERVED_WORDS.
 * @param {boolean=} opt_includeInstance Whether to include the JSPB instance
 *     for transitional soy proto support: http://goto/soy-param-migration
 * @return {!Object}
 */
proto.booksPb.BookCategory.prototype.toObject = function(opt_includeInstance) {
  return proto.booksPb.BookCategory.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Whether to include the JSPB
 *     instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.booksPb.BookCategory} msg The msg instance to transform.
 * @return {!Object}
 */
proto.booksPb.BookCategory.toObject = function(includeInstance, msg) {
  var f, obj = {
    id: jspb.Message.getFieldWithDefault(msg, 1, 0),
    name: jspb.Message.getFieldWithDefault(msg, 2, ""),
    isparent: jspb.Message.getFieldWithDefault(msg, 3, false)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.booksPb.BookCategory}
 */
proto.booksPb.BookCategory.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.booksPb.BookCategory;
  return proto.booksPb.BookCategory.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.booksPb.BookCategory} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.booksPb.BookCategory}
 */
proto.booksPb.BookCategory.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {number} */ (reader.readInt64());
      msg.setId(value);
      break;
    case 2:
      var value = /** @type {string} */ (reader.readString());
      msg.setName(value);
      break;
    case 3:
      var value = /** @type {boolean} */ (reader.readBool());
      msg.setIsparent(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.booksPb.BookCategory.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.booksPb.BookCategory.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.booksPb.BookCategory} message
 * @param {!jspb.BinaryWriter} writer
 */
proto.booksPb.BookCategory.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getId();
  if (f !== 0) {
    writer.writeInt64(
      1,
      f
    );
  }
  f = message.getName();
  if (f.length > 0) {
    writer.writeString(
      2,
      f
    );
  }
  f = message.getIsparent();
  if (f) {
    writer.writeBool(
      3,
      f
    );
  }
};


/**
 * optional int64 id = 1;
 * @return {number}
 */
proto.booksPb.BookCategory.prototype.getId = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 1, 0));
};


/** @param {number} value */
proto.booksPb.BookCategory.prototype.setId = function(value) {
  jspb.Message.setField(this, 1, value);
};


/**
 * optional string name = 2;
 * @return {string}
 */
proto.booksPb.BookCategory.prototype.getName = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 2, ""));
};


/** @param {string} value */
proto.booksPb.BookCategory.prototype.setName = function(value) {
  jspb.Message.setField(this, 2, value);
};


/**
 * optional bool isParent = 3;
 * Note that Boolean fields may be set to 0/1 when serialized from a Java server.
 * You should avoid comparisons like {@code val === true/false} in those cases.
 * @return {boolean}
 */
proto.booksPb.BookCategory.prototype.getIsparent = function() {
  return /** @type {boolean} */ (jspb.Message.getFieldWithDefault(this, 3, false));
};


/** @param {boolean} value */
proto.booksPb.BookCategory.prototype.setIsparent = function(value) {
  jspb.Message.setField(this, 3, value);
};



/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.booksPb.BookMap = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, proto.booksPb.BookMap.repeatedFields_, null);
};
goog.inherits(proto.booksPb.BookMap, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  proto.booksPb.BookMap.displayName = 'proto.booksPb.BookMap';
}
/**
 * List of repeated fields within this message type.
 * @private {!Array<number>}
 * @const
 */
proto.booksPb.BookMap.repeatedFields_ = [2];



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto suitable for use in Soy templates.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     com.google.apps.jspb.JsClassTemplate.JS_RESERVED_WORDS.
 * @param {boolean=} opt_includeInstance Whether to include the JSPB instance
 *     for transitional soy proto support: http://goto/soy-param-migration
 * @return {!Object}
 */
proto.booksPb.BookMap.prototype.toObject = function(opt_includeInstance) {
  return proto.booksPb.BookMap.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Whether to include the JSPB
 *     instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.booksPb.BookMap} msg The msg instance to transform.
 * @return {!Object}
 */
proto.booksPb.BookMap.toObject = function(includeInstance, msg) {
  var f, obj = {
    count: jspb.Message.getFieldWithDefault(msg, 1, 0),
    bookList: jspb.Message.toObjectList(msg.getBookList(),
    proto.booksPb.Book.toObject, includeInstance)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.booksPb.BookMap}
 */
proto.booksPb.BookMap.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.booksPb.BookMap;
  return proto.booksPb.BookMap.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.booksPb.BookMap} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.booksPb.BookMap}
 */
proto.booksPb.BookMap.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {number} */ (reader.readInt64());
      msg.setCount(value);
      break;
    case 2:
      var value = new proto.booksPb.Book;
      reader.readMessage(value,proto.booksPb.Book.deserializeBinaryFromReader);
      msg.addBook(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.booksPb.BookMap.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.booksPb.BookMap.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.booksPb.BookMap} message
 * @param {!jspb.BinaryWriter} writer
 */
proto.booksPb.BookMap.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getCount();
  if (f !== 0) {
    writer.writeInt64(
      1,
      f
    );
  }
  f = message.getBookList();
  if (f.length > 0) {
    writer.writeRepeatedMessage(
      2,
      f,
      proto.booksPb.Book.serializeBinaryToWriter
    );
  }
};


/**
 * optional int64 count = 1;
 * @return {number}
 */
proto.booksPb.BookMap.prototype.getCount = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 1, 0));
};


/** @param {number} value */
proto.booksPb.BookMap.prototype.setCount = function(value) {
  jspb.Message.setField(this, 1, value);
};


/**
 * repeated Book book = 2;
 * If you change this array by adding, removing or replacing elements, or if you
 * replace the array itself, then you must call the setter to update it.
 * @return {!Array.<!proto.booksPb.Book>}
 */
proto.booksPb.BookMap.prototype.getBookList = function() {
  return /** @type{!Array.<!proto.booksPb.Book>} */ (
    jspb.Message.getRepeatedWrapperField(this, proto.booksPb.Book, 2));
};


/** @param {!Array.<!proto.booksPb.Book>} value */
proto.booksPb.BookMap.prototype.setBookList = function(value) {
  jspb.Message.setRepeatedWrapperField(this, 2, value);
};


/**
 * @param {!proto.booksPb.Book=} opt_value
 * @param {number=} opt_index
 * @return {!proto.booksPb.Book}
 */
proto.booksPb.BookMap.prototype.addBook = function(opt_value, opt_index) {
  return jspb.Message.addToRepeatedWrapperField(this, 2, opt_value, proto.booksPb.Book, opt_index);
};


proto.booksPb.BookMap.prototype.clearBookList = function() {
  this.setBookList([]);
};



/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.booksPb.GetBookRequest = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.booksPb.GetBookRequest, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  proto.booksPb.GetBookRequest.displayName = 'proto.booksPb.GetBookRequest';
}


if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto suitable for use in Soy templates.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     com.google.apps.jspb.JsClassTemplate.JS_RESERVED_WORDS.
 * @param {boolean=} opt_includeInstance Whether to include the JSPB instance
 *     for transitional soy proto support: http://goto/soy-param-migration
 * @return {!Object}
 */
proto.booksPb.GetBookRequest.prototype.toObject = function(opt_includeInstance) {
  return proto.booksPb.GetBookRequest.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Whether to include the JSPB
 *     instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.booksPb.GetBookRequest} msg The msg instance to transform.
 * @return {!Object}
 */
proto.booksPb.GetBookRequest.toObject = function(includeInstance, msg) {
  var f, obj = {
    isbn: jspb.Message.getFieldWithDefault(msg, 1, 0)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.booksPb.GetBookRequest}
 */
proto.booksPb.GetBookRequest.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.booksPb.GetBookRequest;
  return proto.booksPb.GetBookRequest.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.booksPb.GetBookRequest} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.booksPb.GetBookRequest}
 */
proto.booksPb.GetBookRequest.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {number} */ (reader.readInt64());
      msg.setIsbn(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.booksPb.GetBookRequest.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.booksPb.GetBookRequest.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.booksPb.GetBookRequest} message
 * @param {!jspb.BinaryWriter} writer
 */
proto.booksPb.GetBookRequest.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getIsbn();
  if (f !== 0) {
    writer.writeInt64(
      1,
      f
    );
  }
};


/**
 * optional int64 isbn = 1;
 * @return {number}
 */
proto.booksPb.GetBookRequest.prototype.getIsbn = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 1, 0));
};


/** @param {number} value */
proto.booksPb.GetBookRequest.prototype.setIsbn = function(value) {
  jspb.Message.setField(this, 1, value);
};



/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.booksPb.GetBookViaAuthorRequest = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.booksPb.GetBookViaAuthorRequest, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  proto.booksPb.GetBookViaAuthorRequest.displayName = 'proto.booksPb.GetBookViaAuthorRequest';
}


if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto suitable for use in Soy templates.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     com.google.apps.jspb.JsClassTemplate.JS_RESERVED_WORDS.
 * @param {boolean=} opt_includeInstance Whether to include the JSPB instance
 *     for transitional soy proto support: http://goto/soy-param-migration
 * @return {!Object}
 */
proto.booksPb.GetBookViaAuthorRequest.prototype.toObject = function(opt_includeInstance) {
  return proto.booksPb.GetBookViaAuthorRequest.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Whether to include the JSPB
 *     instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.booksPb.GetBookViaAuthorRequest} msg The msg instance to transform.
 * @return {!Object}
 */
proto.booksPb.GetBookViaAuthorRequest.toObject = function(includeInstance, msg) {
  var f, obj = {
    author: jspb.Message.getFieldWithDefault(msg, 1, "")
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.booksPb.GetBookViaAuthorRequest}
 */
proto.booksPb.GetBookViaAuthorRequest.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.booksPb.GetBookViaAuthorRequest;
  return proto.booksPb.GetBookViaAuthorRequest.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.booksPb.GetBookViaAuthorRequest} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.booksPb.GetBookViaAuthorRequest}
 */
proto.booksPb.GetBookViaAuthorRequest.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readString());
      msg.setAuthor(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.booksPb.GetBookViaAuthorRequest.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.booksPb.GetBookViaAuthorRequest.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.booksPb.GetBookViaAuthorRequest} message
 * @param {!jspb.BinaryWriter} writer
 */
proto.booksPb.GetBookViaAuthorRequest.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getAuthor();
  if (f.length > 0) {
    writer.writeString(
      1,
      f
    );
  }
};


/**
 * optional string author = 1;
 * @return {string}
 */
proto.booksPb.GetBookViaAuthorRequest.prototype.getAuthor = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
};


/** @param {string} value */
proto.booksPb.GetBookViaAuthorRequest.prototype.setAuthor = function(value) {
  jspb.Message.setField(this, 1, value);
};



/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.booksPb.UpdateBookRequest = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.booksPb.UpdateBookRequest, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  proto.booksPb.UpdateBookRequest.displayName = 'proto.booksPb.UpdateBookRequest';
}


if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto suitable for use in Soy templates.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     com.google.apps.jspb.JsClassTemplate.JS_RESERVED_WORDS.
 * @param {boolean=} opt_includeInstance Whether to include the JSPB instance
 *     for transitional soy proto support: http://goto/soy-param-migration
 * @return {!Object}
 */
proto.booksPb.UpdateBookRequest.prototype.toObject = function(opt_includeInstance) {
  return proto.booksPb.UpdateBookRequest.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Whether to include the JSPB
 *     instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.booksPb.UpdateBookRequest} msg The msg instance to transform.
 * @return {!Object}
 */
proto.booksPb.UpdateBookRequest.toObject = function(includeInstance, msg) {
  var f, obj = {
    isbn: jspb.Message.getFieldWithDefault(msg, 1, ""),
    book: (f = msg.getBook()) && proto.booksPb.Book.toObject(includeInstance, f)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.booksPb.UpdateBookRequest}
 */
proto.booksPb.UpdateBookRequest.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.booksPb.UpdateBookRequest;
  return proto.booksPb.UpdateBookRequest.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.booksPb.UpdateBookRequest} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.booksPb.UpdateBookRequest}
 */
proto.booksPb.UpdateBookRequest.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readString());
      msg.setIsbn(value);
      break;
    case 2:
      var value = new proto.booksPb.Book;
      reader.readMessage(value,proto.booksPb.Book.deserializeBinaryFromReader);
      msg.setBook(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.booksPb.UpdateBookRequest.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.booksPb.UpdateBookRequest.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.booksPb.UpdateBookRequest} message
 * @param {!jspb.BinaryWriter} writer
 */
proto.booksPb.UpdateBookRequest.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getIsbn();
  if (f.length > 0) {
    writer.writeString(
      1,
      f
    );
  }
  f = message.getBook();
  if (f != null) {
    writer.writeMessage(
      2,
      f,
      proto.booksPb.Book.serializeBinaryToWriter
    );
  }
};


/**
 * optional string isbn = 1;
 * @return {string}
 */
proto.booksPb.UpdateBookRequest.prototype.getIsbn = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
};


/** @param {string} value */
proto.booksPb.UpdateBookRequest.prototype.setIsbn = function(value) {
  jspb.Message.setField(this, 1, value);
};


/**
 * optional Book book = 2;
 * @return {?proto.booksPb.Book}
 */
proto.booksPb.UpdateBookRequest.prototype.getBook = function() {
  return /** @type{?proto.booksPb.Book} */ (
    jspb.Message.getWrapperField(this, proto.booksPb.Book, 2));
};


/** @param {?proto.booksPb.Book|undefined} value */
proto.booksPb.UpdateBookRequest.prototype.setBook = function(value) {
  jspb.Message.setWrapperField(this, 2, value);
};


proto.booksPb.UpdateBookRequest.prototype.clearBook = function() {
  this.setBook(undefined);
};


/**
 * Returns whether this field is set.
 * @return {!boolean}
 */
proto.booksPb.UpdateBookRequest.prototype.hasBook = function() {
  return jspb.Message.getField(this, 2) != null;
};


goog.object.extend(exports, proto.booksPb);
